# Generated by Erlang.mk. Edit at your own risk!

src/register_handler.erl:: src/client.erl src/helper.erl; @touch $@
src/twitterws_app.erl:: src/client.erl src/twitter.erl; @touch $@

COMPILE_FIRST += helper client twitter
